version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - parser
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    ports:
      - "8001:8001"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - parser
