site_name: Документация Тайм-менеджера
theme:
  name: material
nav:
  - Главная: index.md
  - Лабораторная работа №1: lab_1.md
  - Практика №1: practice_1.md
  - Лабораторная работа №2: lab_2.md
  - Лабораторная работа №3: lab_3.md
